INSERT INTO WORKER (NAME, DAILY_INCOME) values ('leonardo', 1020.20);
INSERT INTO WORKER (NAME, DAILY_INCOME) values ('Vinicius', 3000.20);
INSERT INTO WORKER (NAME, DAILY_INCOME) values ('Klebson', 24990.20);